name: Build and Publish Python Package

on:
  push:
    branches:
      - main  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: |
        cd app  # Navigate to the app directory
        python setup.py sdist bdist_wheel

    - name: Publish to TestPyPI
      if: github.ref == 'refs/heads/main'  # Only run this step for pushes to the main branch
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Set this in your repo secrets
      run: |
        twine upload --repository testpypi dist/*