name: Build Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch; adjust as needed

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./app  # Path to your Dockerfile and build context
        file: ./app/Dockerfile
        push: false  # Set to true if you want to push to Docker Hub or any other registry
        tags: cdaprod/minio-weaviate-langchain:latest  # Customize this for your Docker Hub username/repository:tag
        load: true  # If pushing is disabled, load the image into Docker

    # Optional: Push the Docker image to a registry
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        docker push cdaprod/minio-weaviate-langchain:lastest