name: Weaviate Deployment and Data Ingestion

on:
  push:
    branches:
      - main

jobs:
  deploy-and-ingest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start Docker Compose Services
      run: docker-compose up -d

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Weaviate Client
      run: pip install weaviate-client

    - name: Run Script
      run: python ./weaviate/script.py

    - name: Fetch and Save Logs
      run: |
        docker logs minio_server > minio.log
        docker logs weaviate_server > weaviate.log

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'David Cannan Cdaprod'
        git config --global user.email 'cdaprod@cdaprod.dev'
        git add .
        git commit -m "Add new files and logs via Github Workflow"
        git push